library(tidyverse)
install.packages("janitor")
library(janitor)
library(readxl)
queens <- read_xls(path="ThisPC/Documents/Quant_stats_HW_Hannah_Fette/datasets/rollingsales_queens.xls", skip=4)
file.path(rollingsales_queens.xls)
getwd()
queens <- read_xls("rollingsales_queens.xls", skip=4)
queens
queens_csv_base <- read.csv("rollingsales_queens_csv.csv", skip=4)
queens_csv_readr <- read_csv("rollingsales_queens_csv.csv", skip=4)
glimpse(queens_csv_base)
glimpse(queens_csv_readr)
glimpse(queens)
brooklyn <- read_excel("rollingsales_brooklyn.xls", skip=4)
bronx <- read_excel("rollingsales_bronx.xls", skip=4)
manhattan <- read_excel("rollingsales_manhattan.xls", skip=4)
delete("manhatten")
remove("manhatten")
staten_island <- read_excel("rollingsales_statenisland.xls", skip=4)
NYC_property_sales <- bind_rows(brooklyn, bronx, manhattan, staten_island, queens)
glimpse(NYC_property_sales)
colnames(brooklyn)
colnames(brooklyn) <- colnames(brooklyn) %>% str_to_title()
colnames(brooklyn)
remove(brooklyn)
brooklyn <- read_excel("rollingsales_brooklyn.xls", skip=4)
colnames(brooklyn)
colnames(brooklyn) <- colnames(brooklyn) %>% str_to_title()
colnames(brooklyn)
colnames(brooklyn) <- colnames(brooklyn) %>% str_replace_all(" ", "_")
colnames(brooklyn)
bronx %>% clean_names()
colnames(bronx) <- colnames(bronx) %>% clean_names()
library(janitor)
install.packages("janitor")
durham_csv_base <- read.csv("nc_durham_2020_04_01.csv")
durham_csv_readr <- read_csv("nc_durham_2020_04_01.csv")
glimpse(durham_csv_base)
